In [1]:
import pandas as pd

In [2]:
online_data=pd.read_excel("online retail.xlsx")

In [3]:
online_data.shape

(541909, 8)

In [4]:
online_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
online_data.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [7]:
online_data.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom

In [8]:
online_data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [9]:
online_data["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [10]:
online_data["Country"].nunique()

38

In [11]:
online_data["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [16]:
france_data=online_data[online_data["Country"]=="France"]

In [18]:
france_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [20]:
france_data.shape

(8557, 8)

In [22]:
france_data.isna().sum()

InvoiceNo       0
StockCode       0
Description     0
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     66
Country         0
dtype: int64

In [24]:
france_pivot=pd.pivot_table(data=france_data,values="Quantity",index="InvoiceNo",columns="Description").fillna(0)

In [26]:
france_encodded=france_pivot.applymap(lambda x:1 if x>0 else 0)

C:\Users\Hariharan\AppData\Local\Temp\ipykernel_15788\2987388617.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  france_encodded=france_pivot.applymap(lambda x:1 if x>0 else 0)

In [27]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
      --------------------------------------- 0.0/1.4 MB 660.6 kB/s eta 0:00:03
     -- ------------------------------------- 0.1/1.4 MB 919.0 kB/s eta 0:00:02
     --- ------------------------------------ 0.1/1.4 MB 901.1 kB/s eta 0:00:02
     ------ --------------------------------- 0.2/1.4 MB 1.4 MB/s eta 0:00:01
     ---------- ----------------------------- 0.4/1.4 MB 1.5 MB/s eta 0:00:01
     ---------------- ----------------------- 0.6/1.4 MB 2.0 MB/s eta 0:00:01
     ----------------------- ---------------- 0.8/1.4 MB 2.4 MB/s eta 0:00:01
     -------------------------------- ------- 1.1/1.4 MB 3.1 MB/s eta 0:00:01
     -------------------------------------- - 1.3/1.4 MB 3.2 MB/s eta 0:00:01
     ---------------------------------------- 1.4/1.4 MB 3.2 MB/s eta 0:00:00
  Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
     -------- ------------------------------- 0.3/1.4 MB 5.9 MB/s eta 0:00:01
     ---------------- ----------------------- 0.6/1.4 MB 7.0 MB/s eta 0:00:01
     --------------------------- ------------ 0.9/1.4 MB 7.3 MB/s eta 0:00:01
     ---------------------------- ----------- 1.0/1.4 MB 6.0 MB/s eta 0:00:01
     ----------------------------------- ---- 1.2/1.4 MB 5.4 MB/s eta 0:00:01
     ---------------------------------------  1.4/1.4 MB 5.4 MB/s eta 0:00:01
     ---------------------------------------- 1.4/1.4 MB 4.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.2 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (2.2.6)
Requirement already satisfied: joblib>=0.13.2 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: pandas>=0.24.2 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (3.10.7)
Requirement already satisfied: scipy>=1.2.1 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.7.2)
Requirement already satisfied: pyparsing>=3 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.5)
Requirement already satisfied: pillow>=8 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (12.0.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.60.1)
Requirement already satisfied: cycler>=0.10 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\hariharan\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
from mlxtend.frequent_patterns import apriori, association_rules

In [31]:
frequent_itemset=apriori(france_encodded,min_support=0.05,use_colnames=True)

In [32]:
frequent_itemset

      support                                           itemsets
0    0.060738                      (4 TRADITIONAL SPINNING TOPS)
1    0.082430                       (ALARM CLOCK BAKELIKE GREEN)
2    0.086768                        (ALARM CLOCK BAKELIKE PINK)
3    0.080260                        (ALARM CLOCK BAKELIKE RED )
4    0.058568                       (ASSORTED COLOUR MINI CASES)
..        ...                                                ...
124  0.071584  (SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...
125  0.071584  (SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...
126  0.086768  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...
127  0.084599  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...
128  0.069414  (SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...

[129 rows x 2 columns]

In [35]:
best_association = association_rules(frequent_itemset,)

In [36]:
best_association

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.080260,0.082430,0.067245,0.837838,10.164296,1.0,0.060629,5.658351,0.980295,0.704545,0.823270,0.826814
1,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.082430,0.080260,0.067245,0.815789,10.164296,1.0,0.060629,4.992873,0.982613,0.704545,0.799714,0.826814
2,(ALARM CLOCK BAKELIKE GREEN),(POSTAGE),0.082430,0.650759,0.071584,0.868421,1.334474,1.0,0.017942,2.654230,0.273157,0.108197,0.623243,0.489211
3,(ALARM CLOCK BAKELIKE PINK),(POSTAGE),0.086768,0.650759,0.075922,0.875000,1.344583,1.0,0.019457,2.793926,0.280624,0.114754,0.642081,0.495833
4,(ALARM CLOCK BAKELIKE RED ),(POSTAGE),0.080260,0.650759,0.073753,0.918919,1.412072,1.0,0.021523,4.307303,0.317286,0.112211,0.767836,0.516126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,"(SET/6 RED SPOTTY PAPER PLATES, POSTAGE, SET/2...",(SET/6 RED SPOTTY PAPER CUPS),0.071584,0.117137,0.069414,0.969697,8.278339,1.0,0.061029,29.134490,0.946992,0.581818,0.965676,0.781145
62,"(POSTAGE, SET/6 RED SPOTTY PAPER CUPS, SET/20 ...",(SET/6 RED SPOTTY PAPER PLATES),0.071584,0.108460,0.069414,0.969697,8.940606,1.0,0.061650,29.420824,0.956630,0.627451,0.966010,0.804848
63,"(SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...",(SET/20 RED RETROSPOT PAPER NAPKINS ),0.086768,0.112798,0.069414,0.800000,7.092308,1.0,0.059627,4.436009,0.940618,0.533333,0.774572,0.707692
64,"(SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...","(SET/6 RED SPOTTY PAPER CUPS, POSTAGE)",0.086768,0.099783,0.069414,0.800000,8.017391,1.0,0.060756,4.501085,0.958432,0.592593,0.777831,0.747826
65,"(SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...","(SET/6 RED SPOTTY PAPER PLATES, POSTAGE)",0.086768,0.091106,0.069414,0.800000,8.780952,1.0,0.061509,4.544469,0.970309,0.640000,0.779952,0.780952